/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package sean.kafka_streams_poc.avro.domain;
@org.apache.avro.specific.AvroGenerated
public enum Entity implements org.apache.avro.generic.GenericEnumSymbol<Entity> {
  Bloomberg, TradeWeb, Traiana  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Entity\",\"namespace\":\"sean.kafka_streams_poc.avro.domain\",\"symbols\":[\"Bloomberg\",\"TradeWeb\",\"Traiana\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  public static Entity parse(String val) {
    for (Entity en: Entity.values()) {
      if (en.name().equalsIgnoreCase(val)) {
        return en;
      }
    }
    return null;
  }

  public static Entity fromEntity(sean.kafka_streams_poc.domain.Entity e) {
    return Entity.valueOf(e.name());
  }
}
