/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package sean.kafka_streams_poc.avro.domain;
@org.apache.avro.specific.AvroGenerated
public enum TokenType implements org.apache.avro.generic.GenericEnumSymbol<TokenType> {
  EventToken, AllocToken  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"TokenType\",\"namespace\":\"sean.kafka_streams_poc.avro.domain\",\"symbols\":[\"EventToken\",\"AllocToken\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  public static TokenType parse(String val) {
    for (TokenType tt: TokenType.values()) {
      if (tt.name().equalsIgnoreCase(val)) {
        return tt;
      }
    }
    return null;
  }

  public static TokenType fromTokenType(sean.kafka_streams_poc.domain.TokenType tokenType) {
    return TokenType.valueOf(tokenType.name());
  }
}
